[build]
  publish = "."

[[redirects]]
  from = "https://www.acesmolding.com/*"
  to = "https://acesmolding.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.acesmolding.com/*"
  to = "https://acesmolding.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://acesmolding.com/*"
  to = "https://acesmolding.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
